server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create